// lib/mock-data.ts
// Best Tools — Test ma'lumotlari (haqiqiy DB ulanguncha)

export const mockBrands = [
  {
    id: "1",
    name: "Bosch",
    slug: "bosch",
    logo: "/images/brands/bosch.svg",
    description: "Nemis sifati, professional sifat",
    descriptionRu: "Немецкое качество, профессиональный инструмент",
  },
  {
    id: "2",
    name: "Milwaukee",
    slug: "milwaukee",
    logo: "/images/brands/milwaukee.svg",
    description: "Professional elektr asboblar",
    descriptionRu: "Профессиональный электроинструмент премиум класса",
  },
  {
    id: "3",
    name: "DeWalt",
    slug: "dewalt",
    logo: "/images/brands/dewalt.svg",
    description: "Qurilish professionals uchun",
    descriptionRu: "Инструменты для настоящих профессионалов строительства",
  },
  {
    id: "4",
    name: "Makita",
    slug: "makita",
    logo: "/images/brands/makita.svg",
    description: "Yaponiya sifati",
    descriptionRu: "Настоящее японское качество и надежность",
  },
  {
    id: "5",
    name: "Hilti",
    slug: "hilti",
    logo: "/images/brands/hilti.svg",
    description: "Premium professional asboblar",
    descriptionRu: "Профессиональные инструменты премиум-сегмента",
  },
  {
    id: "6",
    name: "Metabo",
    slug: "metabo",
    logo: "/images/brands/metabo.svg",
    description: "Ishonchli ishlab chiqaruvchi",
    descriptionRu: "Надежный немецкий производитель оборудования",
  },
];

export const mockCategories = [
  {
    id: "1",
    name: "Drellar",
    nameRu: "Дрели",
    slug: "drills",
    image: "/images/categories/drill.jpg",
    count: 48,
    icon: "drill",
  },
  {
    id: "2",
    name: "Bolg'achalar",
    nameRu: "Молотки и перфораторы",
    slug: "hammers",
    image: "/images/categories/hammer.jpg",
    count: 32,
    icon: "hammer",
  },
  {
    id: "3",
    name: "Arra mashinalar",
    nameRu: "Пилы",
    slug: "saws",
    image: "/images/categories/saw.jpg",
    count: 27,
    icon: "saw",
  },
  {
    id: "4",
    name: "Silliqlash",
    nameRu: "Шлифовальные машины",
    slug: "grinders",
    image: "/images/categories/grinder.jpg",
    count: 35,
    icon: "grinder",
  },
  {
    id: "5",
    name: "Shurупovyortlar",
    nameRu: "Шуруповёрты",
    slug: "screwdrivers",
    image: "/images/categories/screwdriver.jpg",
    count: 41,
    icon: "screwdriver",
  },
  {
    id: "6",
    name: "Payvandlash",
    nameRu: "Сварочные аппараты",
    slug: "welding",
    image: "/images/categories/welding.jpg",
    count: 19,
    icon: "welding",
  },
];

export const mockProducts = [
  {
    id: "1",
    name: "Bosch GSB 18V-50 Professional",
    nameRu: "Bosch GSB 18V-50 Professional",
    slug: "bosch-gsb-18v-50-professional",
    sku: "GSB-18V-50",
    shortDesc: "Akkumulyatorli zarbali drel, 18V, 50Nm",
    price: 2890000,
    oldPrice: 3200000,
    stock: 15,
    brand: { name: "Bosch", slug: "bosch" },
    category: { name: "Drellar", slug: "drills" },
    images: ["/images/products/bosch-gsb-18v.jpg"],
    rating: 4.8,
    isFeatured: true,
    installmentAvailable: true,
    specs: {
      voltage: "18V",
      power: "50Nm",
      maxDrill: "13mm",
      weight: "1.9kg",
    },
  },
  {
    id: "2",
    name: "Milwaukee M18 FUEL 2803-20",
    nameRu: "Milwaukee M18 FUEL 2803-20",
    slug: "milwaukee-m18-fuel-2803-20",
    sku: "M18-FUEL-2803",
    shortDesc: "18V akkumulyatorli drel-shurупovyort",
    price: 4150000,
    oldPrice: null,
    stock: 8,
    brand: { name: "Milwaukee", slug: "milwaukee" },
    category: { name: "Drellar", slug: "drills" },
    images: ["/images/products/milwaukee-m18.jpg"],
    rating: 4.9,
    isFeatured: true,
    installmentAvailable: true,
    specs: {
      voltage: "18V",
      torque: "60Nm",
      speed: "0-2000rpm",
      weight: "1.7kg",
    },
  },
  {
    id: "3",
    name: "DeWalt DCD796P2 XR FlexVolt",
    nameRu: "DeWalt DCD796P2 XR FlexVolt",
    slug: "dewalt-dcd796p2-xr-flexvolt",
    sku: "DCD796P2",
    shortDesc: "18V XR brushless drel-shurупovyort, 2x5Ah",
    price: 5200000,
    oldPrice: 5800000,
    stock: 5,
    brand: { name: "DeWalt", slug: "dewalt" },
    category: { name: "Drellar", slug: "drills" },
    images: ["/images/products/dewalt-dcd796.jpg"],
    rating: 4.7,
    isFeatured: true,
    installmentAvailable: true,
    specs: {
      voltage: "18V",
      torque: "70Nm",
      clutch: "22 pozitsiya",
      weight: "2.1kg",
    },
  },
  {
    id: "4",
    name: "Makita HR2630 Perforator",
    nameRu: "Makita HR2630 Перфоратор",
    slug: "makita-hr2630-perforator",
    sku: "HR2630",
    shortDesc: "SDS-Plus perforator, 800W, 2.7J",
    price: 1950000,
    oldPrice: null,
    stock: 22,
    brand: { name: "Makita", slug: "makita" },
    category: { name: "Bolg'achalar", slug: "hammers" },
    images: ["/images/products/makita-hr2630.jpg"],
    rating: 4.6,
    isFeatured: true,
    installmentAvailable: true,
    specs: {
      power: "800W",
      energy: "2.7J",
      speed: "0-1100rpm",
      weight: "2.9kg",
    },
  },
  {
    id: "5",
    name: "Bosch GWS 900-125 Professional",
    nameRu: "Bosch GWS 900-125 Professional",
    slug: "bosch-gws-900-125-professional",
    sku: "GWS-900-125",
    shortDesc: "Burchak silliqlash mashina, 900W, 125mm disk",
    price: 890000,
    oldPrice: 1100000,
    stock: 30,
    brand: { name: "Bosch", slug: "bosch" },
    category: { name: "Silliqlash", slug: "grinders" },
    images: ["/images/products/bosch-gws900.jpg"],
    rating: 4.5,
    isFeatured: false,
    installmentAvailable: false,
    specs: {
      power: "900W",
      disk: "125mm",
      speed: "11000rpm",
      weight: "1.7kg",
    },
  },
  {
    id: "6",
    name: "Milwaukee M12 FUEL 2404-20",
    nameRu: "Milwaukee M12 FUEL 2404-20",
    slug: "milwaukee-m12-fuel-2404-20",
    sku: "M12-FUEL-2404",
    shortDesc: "12V compact drel-shurупovyort, brushless motor",
    price: 2100000,
    oldPrice: null,
    stock: 12,
    brand: { name: "Milwaukee", slug: "milwaukee" },
    category: { name: "Drellar", slug: "drills" },
    images: ["/images/products/milwaukee-m12.jpg"],
    rating: 4.7,
    isFeatured: false,
    installmentAvailable: true,
    specs: {
      voltage: "12V",
      torque: "34Nm",
      speed: "0-1800rpm",
      weight: "0.7kg",
    },
  },
  {
    id: "7",
    name: "DeWalt DCS391P1 XR Dairali Arra",
    nameRu: "DeWalt DCS391P1 XR Циркулярная пила",
    slug: "dewalt-dcs391p1-xr-circular-saw",
    sku: "DCS391P1",
    shortDesc: "18V XR akkumulyatorli dairali arra, 165mm",
    price: 3750000,
    oldPrice: 4200000,
    stock: 7,
    brand: { name: "DeWalt", slug: "dewalt" },
    category: { name: "Arra mashinalar", slug: "saws" },
    images: ["/images/products/dewalt-dcs391.jpg"],
    rating: 4.8,
    isFeatured: true,
    installmentAvailable: true,
    specs: {
      voltage: "18V",
      blade: "165mm",
      depth: "57mm",
      weight: "3.3kg",
    },
  },
  {
    id: "8",
    name: "Hilti TE 30-A36 Perforator",
    nameRu: "Hilti TE 30-A36 Перфоратор",
    slug: "hilti-te-30-a36-perforator",
    sku: "TE-30-A36",
    shortDesc: "36V professional SDS-Plus perforator, 3.2J",
    price: 8900000,
    oldPrice: null,
    stock: 3,
    brand: { name: "Hilti", slug: "hilti" },
    category: { name: "Bolg'achalar", slug: "hammers" },
    images: ["/images/products/hilti-te30.jpg"],
    rating: 5.0,
    isFeatured: true,
    installmentAvailable: true,
    specs: {
      voltage: "36V",
      energy: "3.2J",
      speed: "0-900rpm",
      weight: "3.8kg",
    },
  },
];

export const formatPrice = (price: number, lang: string = "uz"): string => {
  const formatted = new Intl.NumberFormat(lang === "ru" ? "ru-RU" : "uz-UZ", {
    style: "decimal",
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
  return lang === "ru" ? `${formatted} сум` : `${formatted} so'm`;
};

export const calculateDiscount = (price: number, oldPrice: number): number => {
  return Math.round(((oldPrice - price) / oldPrice) * 100);
};
